linters:
  enable:
  - asciicheck
  - bodyclose
  - deadcode
  - depguard
  - dogsled
  - durationcheck
  - errcheck
  - errorlint
  - exportloopref
  - gci
  - gofmt
  - gofumpt
  - goimports
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - megacheck
  - misspell
  - nakedret
  - nolintlint
  - revive
  - staticcheck
  - structcheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck
  - wastedassign
