name: 'Gosec Security Checker'
description: 'Runs the gosec security checker'
author: '@ccojocar'

inputs:
  version:
    description: 'Version of gosec to use (e.g. 2.15.0)'
    required: false
    default: 'latest'
  args:
    description: 'Arguments for gosec'
    required: true
    default: '-h'

runs:
    using: 'docker'
    image: 'docker://securego/gosec'
    args:
      - ${{ inputs.args }}

branding:
  icon: 'shield'
  color: 'blue'
