name: 'Gosec Security Checker'
description: 'Runs the gosec security checker'
author: '@ccojocar'

inputs:
  args:
    description: 'Arguments for gosec'
    required: true
    default: '-h'

runs:
    using: 'docker'
    image: 'docker://securego/gosec:2.21.1'
    args:
      - ${{ inputs.args }}

branding:
  icon: 'shield'
  color: 'blue'
