name: "Gosec Security Checker"
description: "Runs the gosec security checker"
author: "@ccojocar"

inputs:
  args:
    description: "Arguments for gosec"
    required: true
    default: "-h"

runs:
  using: "docker"
  image: "docker://ghcr.io/securego/gosec@sha256:d0859f242774504d57b17442b2dc77d4ffd2f4d30fbdf92c7eb612b2a394f477" # 2.27.1
  args:
    - ${{ inputs.args }}

branding:
  icon: "shield"
  color: "blue"
