package main

import "text/template"

var generatedRuleTmpl = template.Must(template.New("generated").Parse(`
// DO NOT EDIT - Generated by tlsconfig
func New{{.Name}}TLSCheck(conf gas.Config) (gas.Rule, []ast.Node) {
	return &insecureConfigTLS{
		requiredType: "crypto/tls.Config",
		MinVersion:   {{ .MinVersion }},
		MaxVersion:   {{ .MaxVersion }},
		goodCiphers: []string{
{{range $cipherName := .Ciphers }} "{{$cipherName}}",
{{end}}
		},
	}, []ast.Node{(*ast.CompositeLit)(nil)}
}
`))
